## Analysis of copy number alteration in HR gene within tumour samples
## Latest update: 29/08/2021
## Version 1.0.0
## Author: Dian Lyu

#load library
library(tidyverse)

#load data: segmented copy number data and ploidy valye generated by ASCAT
read.table('Vortex_HRDgenes_segments_overlaps.txt')
Vortex=read.table('Vortex_HRDgenes_segments_overlaps.txt', header = T)

ploidy = data.frame(read.csv('Vortex_ploidy_values.CSV'))
ploidy = mutate(ploidy, a_ploidy = (2^1.3)*ploidy)

Vortex = left_join(Vortex, ploidy, by = 'sample')

#identify copy number aberation in HR genes for each sample
Vortex = mutate(Vortex, CN_status = NA)
for (i in 1:nrow(Vortex)){
  if (Vortex$nMajor[i] == 0 & Vortex$nMinor[i] == 0) {
    Vortex$CN_status[i] = 'homozygous deletion'
  }
  else if (Vortex$nMajor[i] > 0 & Vortex$nMinor[i] == 0) {
    Vortex$CN_status[i] = 'loss of heterozygosity'
  }
  else if (Vortex$nMajor[i] == 1 & Vortex$nMinor[i] == 1) {
    Vortex$CN_status[i] = 'diploid'
  }
  else if (Vortex$nMajor[i] > 0 & Vortex$nMinor[i] > 0 & Vortex$total_CN[i]<Vortex$a_ploidy[i]) {
    Vortex$CN_status[i] = 'gain'
  }
}

#manually add copy number status for VOR78 BRCA1 (there were two segments identified in BRCA1 in VOR78, and both segments have copy number gains)
Vortex[which(Vortex$sample == 'VOR78' & Vortex$gene == 'BRCA1'),]$CN_status = 'gain'

#output result
write.table(Vortex, file = 'copy_number_change.csv', sep = ',', row.names = FALSE)

#visulise copy number status data by bar plot
#make stacked bar plot, each bar represent a sample
#sort by relative frequency
lvls2 = names(sort(tapply(Vortex_a$CN_status == "loss of heterozygosity", Vortex_a$sample, mean)))
Vortex_a = select(Vortex, sample, gene, CN_status)
ggplot(data = Vortex_a)+
  geom_bar(
    mapping = aes(
      factor(sample, levels = lvls2),
      fill = CN_status),
    position = 'fill'
  )+
  theme(axis.text.x = element_text(angle = 90,vjust =0.25, hjust=0, size = 12))+
  xlab('Sample')

#make a new dataframe containing only LOH and homozygous deletion
Vortex_b = filter(Vortex_a, CN_status=='loss of heterozygosity'| CN_status=='homozygous deletion')
Vortex_c = data.frame(sample = c("VOR208","VOR21","VOR231","VOR253","VOR40","VOR67"),
                      gene = c(NA),
                      CN_status = c("no deletion")
)
Vortex_b = rbind(Vortex_b, Vortex_c)

#make stacked barplot, sorting by relative frequency, color by different types of copy number deletion
ggplot(data = Vortex_b)+
  geom_bar(
    mapping = aes(
      factor(sample,levels = lvls2),
      fill = CN_status)
  )+
  theme(axis.text.x = element_text(angle = 90,vjust =0.25, hjust=0, size = 12))+
  xlab('Sample')+
  scale_fill_manual(values = c("lightblue3","coral","lightgoldenrod" ))

#make stacked barplot, sorting by relative frequency, color by different STS subtypes
Diagnosis=read.csv('D:/R (UCL project)/Vortex study copy number/second/copy_number_change.csv')
Diagnosis=select(Diagnosis,sample:diagnosis)

Vortex_e=left_join(Vortex_b,Diagnosis)
Vortex_e=distinct(Vortex_e)


for (i in 1:nrow(Vortex_e)) {
  if(Vortex_e$diagnosis[i]%in%c('myxoid liposarcoma','leiomyosarcoma','malignant peripheral nerve sheath tumour','myxofibrosarcoma','undifferentiated pleomorphic sarcoma')){
    Vortex_e$diagnosis[i]=Vortex_e$diagnosis[i]
  }else{
    Vortex_e$diagnosis[i]='other'
  }
}

ggplot(data = Vortex_e)+
  geom_bar(
    mapping = aes(
      factor(sample,levels = lvls2),
      fill = diagnosis)
  )

#make stacked bar plot, each bar represent a gene, sorting by relative frequency
lvls3 = names(sort(tapply(Vortex_a$CN_status == "loss of heterozygosity", Vortex_a$gene, mean), decreasing = TRUE))
ggplot(data = Vortex_a)+
  geom_bar(
    mapping = aes(
      factor(gene, levels = lvls3),
      fill = CN_status),
    position = 'fill'
  )+
  theme(axis.text.x = element_text(angle = 30,vjust =0.5, hjust=0.5, size = 12))+
  xlab('Gene')

#make barplot displaying only LOH and homozygous deletion in each HR gene
Vortex_d = filter(Vortex_a, CN_status=='loss of heterozygosity'| CN_status=='homozygous deletion')
ggplot(data = Vortex_d)+
  geom_bar(
    mapping = aes(
      factor(gene, levels = lvls3),
      fill = CN_status)
  )+
  theme(axis.text.x = element_text(angle = 30,vjust =0.5, hjust=0.5, size = 12))+
  xlab('Gene')+
  scale_fill_manual(values = c("lightblue3","coral"))

#####################################################
#identify samples with multiple segments in one gene region
b = select(Vortex, sample, gene)
ind = duplicated(b[,1:2])
c = b[ind,]
multiple_segments =Vortex[1,]
for (i in 1:nrow(Vortex)) {
  for (j in 1:nrow(c)) {
    if (Vortex[i,1]==c[j,1] & Vortex[i,3]==c[j,2]) {
      multiple_segments =rbind(multiple_segments,Vortex[i,])
    }
  }
}
multiple_segments = multiple_segments[-1,]









